server:
  port: 8084

spring:
  application:
    name: ai-recommendation-engine

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ai-recommendation-engine
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.shoppingfeed.common.event"
        spring.json.type.mapping: "userEvent:com.shoppingfeed.common.event.UserEvent"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/shoppingfeed
    username: shopuser
    password: shoppass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.1-8b-instant
          temperature: 0.1
          max-tokens: 1000
      embedding:
        enabled: false
    ollama:
      base-url: http://localhost:11434
      embedding:
        options:
          model: nomic-embed-text
      chat:
        enabled: false

logging:
  level:
    com.shoppingfeed: DEBUG
    org.springframework.ai: INFO