server:
  port: 8083

spring:
  application:
    name: trending-service

  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: trending-streams-app
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    com.shoppingfeed: DEBUG
    org.apache.kafka.streams: INFO